<?php

namespace app\models;

use yii\db\ActiveRecord;
/**
 * Модель для таблицы "News".
 *
 * @property integer $id
 * @property string $header
 * @property string $announcement
 * @property string $maintext
 * @property string $tag
 * @property string $date
 */
class News extends ActiveRecord
{


    public static function tableName()
    {
        return 'news';// TODO: Change the autogenerated stub
    }

    public function rules() {
        return [
            [['id', 'header', 'announcement', 'maintext', 'tag','date'], 'required'],
            [['id'], 'integer'],
            [['header', 'announcement', 'maintext', 'tag','date'], 'string'],
        ];
    }
    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'header' => 'заголовок',
            'announcement' => 'анонс',
            'maintext' => 'основной текс',
            'tag' => 'тег',
            'date'=>'дата'

        ];
    }
    public function getId() {
        return $this->id;
    }
}